name: agenda_diaria
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1

  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Bienvenidoa.png
    - assets/images/LogoKC.jpg
    
  # Para agregar assets, descomenta y modifica según necesites:
  # assets:
  #   - images/
